[package]
name = "rawstdraw"
version = "0.1.0"
authors = ["Ilya Maximov <mail@overlisted.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
mut_static = "5.0.0"
